config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
  CATEGORIES = ["chinese","italian", "japanese", "french", "belgian"]
  validates :address, :category, presence: true
  validates :phone_number, presence: true
  validates :category, inclusion: {in: CATEGORIES, message: "The category is invalid"}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

   private

  # strong params
  def restaurant_params
    params.require(:restaurant).permit(:address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Here are all the restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= restaurant.name %> | <%= link_to "More info", restaurant_path(restaurant) %>
      <%= link_to "Delete", restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary" %>
    </li>
  <% end %>
</ul>

<%= link_to "Add a new restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= form_for(@restaurant)do |r| %>
  <%= r.label :name%>
  <%= r.text_field :name%>
  <%= r.label :address%>
  <%= r.text_field :address%>
  <%= r.label :phone_number%>
  <%= r.text_field :phone_number%>
  <%= r.label :category%>
  <%= r.text_field :category%>
  <%= r.submit %>
<%end%>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p>Address: <%= @restaurant.address %></p>
<p>Phone_number: <%= @restaurant.phone_number %></p>
<p>Category: <%= @restaurant.category %></p>

<%= link_to "Back to all restaurants", restaurants_path %>